[2026-03-29T09:11:56.970Z] [updateUserRoles] DiscordAPIError[50013]: Missing Permissions
    at handleErrors (/home/container/node_modules/@discordjs/rest/dist/index.js:762:13)
    at process.processTicksAndRejections (node:internal/process/task_queues:104:5)
    at async SequentialHandler.runRequest (/home/container/node_modules/@discordjs/rest/dist/index.js:1163:23)
    at async SequentialHandler.queueRequest (/home/container/node_modules/@discordjs/rest/dist/index.js:994:14)
    at async _REST.request (/home/container/node_modules/@discordjs/rest/dist/index.js:1307:22)
    at async GuildMemberManager.edit (/home/container/node_modules/discord.js/src/managers/GuildMemberManager.js:428:15)
    at async updateUserRoles (/home/container/utils/roleManager.js:32:35)
    at async Client.onReady (/home/container/events/ready.js:70:25)
[2026-03-29T09:11:58.768Z] [updateUserRoles] DiscordAPIError[50013]: Missing Permissions
    at handleErrors (/home/container/node_modules/@discordjs/rest/dist/index.js:762:13)
    at process.processTicksAndRejections (node:internal/process/task_queues:104:5)
    at async SequentialHandler.runRequest (/home/container/node_modules/@discordjs/rest/dist/index.js:1163:23)
    at async SequentialHandler.queueRequest (/home/container/node_modules/@discordjs/rest/dist/index.js:994:14)
    at async _REST.request (/home/container/node_modules/@discordjs/rest/dist/index.js:1307:22)
    at async GuildMemberManager.edit (/home/container/node_modules/discord.js/src/managers/GuildMemberManager.js:428:15)
    at async updateUserRoles (/home/container/utils/roleManager.js:32:35)
    at async Client.onReady (/home/container/events/ready.js:70:25)
[2026-03-29T09:12:00.128Z] [updateUserRoles] DiscordAPIError[50013]: Missing Permissions
    at handleErrors (/home/container/node_modules/@discordjs/rest/dist/index.js:762:13)
    at process.processTicksAndRejections (node:internal/process/task_queues:104:5)
    at async SequentialHandler.runRequest (/home/container/node_modules/@discordjs/rest/dist/index.js:1163:23)
    at async SequentialHandler.queueRequest (/home/container/node_modules/@discordjs/rest/dist/index.js:994:14)
    at async _REST.request (/home/container/node_modules/@discordjs/rest/dist/index.js:1307:22)
    at async GuildMemberManager.edit (/home/container/node_modules/discord.js/src/managers/GuildMemberManager.js:428:15)
    at async updateUserRoles (/home/container/utils/roleManager.js:32:35)
    at async Client.onReady (/home/container/events/ready.js:70:25)
[2026-03-29T09:12:02.919Z] [updateUserRoles] DiscordAPIError[50013]: Missing Permissions
    at handleErrors (/home/container/node_modules/@discordjs/rest/dist/index.js:762:13)
    at process.processTicksAndRejections (node:internal/process/task_queues:104:5)
    at async SequentialHandler.runRequest (/home/container/node_modules/@discordjs/rest/dist/index.js:1163:23)
    at async SequentialHandler.queueRequest (/home/container/node_modules/@discordjs/rest/dist/index.js:994:14)
    at async _REST.request (/home/container/node_modules/@discordjs/rest/dist/index.js:1307:22)
    at async GuildMemberManager.edit (/home/container/node_modules/discord.js/src/managers/GuildMemberManager.js:428:15)
    at async updateUserRoles (/home/container/utils/roleManager.js:32:35)
    at async Client.onReady (/home/container/events/ready.js:70:25)
[2026-03-29T09:12:04.447Z] [updateUserRoles] DiscordAPIError[50013]: Missing Permissions
    at handleErrors (/home/container/node_modules/@discordjs/rest/dist/index.js:762:13)
    at process.processTicksAndRejections (node:internal/process/task_queues:104:5)
    at async SequentialHandler.runRequest (/home/container/node_modules/@discordjs/rest/dist/index.js:1163:23)
    at async SequentialHandler.queueRequest (/home/container/node_modules/@discordjs/rest/dist/index.js:994:14)
    at async _REST.request (/home/container/node_modules/@discordjs/rest/dist/index.js:1307:22)
    at async GuildMemberManager.edit (/home/container/node_modules/discord.js/src/managers/GuildMemberManager.js:428:15)
    at async updateUserRoles (/home/container/utils/roleManager.js:32:35)
    at async Client.onReady (/home/container/events/ready.js:70:25)
[2026-03-29T10:36:11.468Z] [updateUserRoles] DiscordAPIError[50013]: Missing Permissions
    at handleErrors (/home/container/node_modules/@discordjs/rest/dist/index.js:762:13)
    at process.processTicksAndRejections (node:internal/process/task_queues:104:5)
    at async SequentialHandler.runRequest (/home/container/node_modules/@discordjs/rest/dist/index.js:1163:23)
    at async SequentialHandler.queueRequest (/home/container/node_modules/@discordjs/rest/dist/index.js:994:14)
    at async _REST.request (/home/container/node_modules/@discordjs/rest/dist/index.js:1307:22)
    at async GuildMemberManager.edit (/home/container/node_modules/discord.js/src/managers/GuildMemberManager.js:428:15)
    at async updateUserRoles (/home/container/utils/roleManager.js:28:35)
    at async handleButtonInteraction (/home/container/handlers/buttons.js:215:25)
    at async Client.<anonymous> (/home/container/index.js:29:33)
[2026-03-29T22:00:11.859Z] [cleanupAbandonedThreads] ConnectTimeoutError: Connect Timeout Error (attempted address: discord.com:443, timeout: 10000ms)
    at onConnectTimeout (/home/container/node_modules/@discordjs/rest/node_modules/undici/lib/core/connect.js:237:24)
    at Immediate._onImmediate (/home/container/node_modules/@discordjs/rest/node_modules/undici/lib/core/connect.js:206:11)
    at process.processImmediate (node:internal/timers:504:21)
[2026-04-01T14:00:14.488Z] [cleanupAbandonedThreads] ConnectTimeoutError: Connect Timeout Error (attempted address: discord.com:443, timeout: 10000ms)
    at onConnectTimeout (/home/container/node_modules/@discordjs/rest/node_modules/undici/lib/core/connect.js:237:24)
    at Immediate._onImmediate (/home/container/node_modules/@discordjs/rest/node_modules/undici/lib/core/connect.js:206:11)
    at process.processImmediate (node:internal/timers:504:21)
[2026-04-02T08:18:07.375Z] [updateUserRoles] DiscordAPIError[50013]: Missing Permissions
    at handleErrors (/home/container/node_modules/@discordjs/rest/dist/index.js:762:13)
    at process.processTicksAndRejections (node:internal/process/task_queues:104:5)
    at async SequentialHandler.runRequest (/home/container/node_modules/@discordjs/rest/dist/index.js:1163:23)
    at async SequentialHandler.queueRequest (/home/container/node_modules/@discordjs/rest/dist/index.js:994:14)
    at async _REST.request (/home/container/node_modules/@discordjs/rest/dist/index.js:1307:22)
    at async GuildMemberManager.edit (/home/container/node_modules/discord.js/src/managers/GuildMemberManager.js:428:15)
    at async updateUserRoles (/home/container/utils/roleManager.js:28:35)
    at async Client.handleMessageCreate (/home/container/handlers/commands.js:257:13)
[2026-04-13T12:22:43.482Z] [updateUserRoles] DiscordAPIError[50013]: Missing Permissions
    at handleErrors (/home/container/node_modules/@discordjs/rest/dist/index.js:762:13)
    at process.processTicksAndRejections (node:internal/process/task_queues:104:5)
    at async SequentialHandler.runRequest (/home/container/node_modules/@discordjs/rest/dist/index.js:1163:23)
    at async SequentialHandler.queueRequest (/home/container/node_modules/@discordjs/rest/dist/index.js:994:14)
    at async _REST.request (/home/container/node_modules/@discordjs/rest/dist/index.js:1307:22)
    at async GuildMemberManager.edit (/home/container/node_modules/discord.js/src/managers/GuildMemberManager.js:428:15)
    at async updateUserRoles (/home/container/utils/roleManager.js:32:35)
    at async Client.onReady (/home/container/events/ready.js:70:25)
[2026-04-13T12:22:45.717Z] [updateUserRoles] DiscordAPIError[50013]: Missing Permissions
    at handleErrors (/home/container/node_modules/@discordjs/rest/dist/index.js:762:13)
    at process.processTicksAndRejections (node:internal/process/task_queues:104:5)
    at async SequentialHandler.runRequest (/home/container/node_modules/@discordjs/rest/dist/index.js:1163:23)
    at async SequentialHandler.queueRequest (/home/container/node_modules/@discordjs/rest/dist/index.js:994:14)
    at async _REST.request (/home/container/node_modules/@discordjs/rest/dist/index.js:1307:22)
    at async GuildMemberManager.edit (/home/container/node_modules/discord.js/src/managers/GuildMemberManager.js:428:15)
    at async updateUserRoles (/home/container/utils/roleManager.js:32:35)
    at async Client.onReady (/home/container/events/ready.js:70:25)
[2026-04-13T12:22:47.136Z] [updateUserRoles] DiscordAPIError[50013]: Missing Permissions
    at handleErrors (/home/container/node_modules/@discordjs/rest/dist/index.js:762:13)
    at process.processTicksAndRejections (node:internal/process/task_queues:104:5)
    at async SequentialHandler.runRequest (/home/container/node_modules/@discordjs/rest/dist/index.js:1163:23)
    at async SequentialHandler.queueRequest (/home/container/node_modules/@discordjs/rest/dist/index.js:994:14)
    at async _REST.request (/home/container/node_modules/@discordjs/rest/dist/index.js:1307:22)
    at async GuildMemberManager.edit (/home/container/node_modules/discord.js/src/managers/GuildMemberManager.js:428:15)
    at async updateUserRoles (/home/container/utils/roleManager.js:32:35)
    at async Client.onReady (/home/container/events/ready.js:70:25)
[2026-04-13T12:22:48.634Z] [updateUserRoles] DiscordAPIError[50013]: Missing Permissions
    at handleErrors (/home/container/node_modules/@discordjs/rest/dist/index.js:762:13)
    at process.processTicksAndRejections (node:internal/process/task_queues:104:5)
    at async SequentialHandler.runRequest (/home/container/node_modules/@discordjs/rest/dist/index.js:1163:23)
    at async SequentialHandler.queueRequest (/home/container/node_modules/@discordjs/rest/dist/index.js:994:14)
    at async _REST.request (/home/container/node_modules/@discordjs/rest/dist/index.js:1307:22)
    at async GuildMemberManager.edit (/home/container/node_modules/discord.js/src/managers/GuildMemberManager.js:428:15)
    at async updateUserRoles (/home/container/utils/roleManager.js:32:35)
    at async Client.onReady (/home/container/events/ready.js:70:25)
[2026-04-13T12:22:50.076Z] [updateUserRoles] DiscordAPIError[50013]: Missing Permissions
    at handleErrors (/home/container/node_modules/@discordjs/rest/dist/index.js:762:13)
    at process.processTicksAndRejections (node:internal/process/task_queues:104:5)
    at async SequentialHandler.runRequest (/home/container/node_modules/@discordjs/rest/dist/index.js:1163:23)
    at async SequentialHandler.queueRequest (/home/container/node_modules/@discordjs/rest/dist/index.js:994:14)
    at async _REST.request (/home/container/node_modules/@discordjs/rest/dist/index.js:1307:22)
    at async GuildMemberManager.edit (/home/container/node_modules/discord.js/src/managers/GuildMemberManager.js:428:15)
    at async updateUserRoles (/home/container/utils/roleManager.js:32:35)
    at async Client.onReady (/home/container/events/ready.js:70:25)
